name='Royas'
print('Hello,\nHow are you?')
print(name)
print(name.upper())
print(name.lower())
print(name.isupper())
print(name.islower())
print(name.upper().isupper())
print(name.lower().islower())
print(len(name))
print(name.index('y'))
print(name.replace('s',`'l'))